Preliminary support for SiDi

diff --git a/bin/jtcore b/bin/jtcore
--- a/bin/jtcore
+++ b/bin/jtcore
@@ -15,6 +15,7 @@ JTCORE compilation tool. (c) Jose Tejada 2019, @topapate
                     JTFRAME_SCAN2X      uses simple scan doubler from JTFRAME
     -git        adds the release file to git
     -mister     compiles MiSTer version. Default is MiST.
+    -sidi       compiles SIDI version. This uses MiST's folders and settings but different pinout
     -prog       programs the FPGA
     -prog-only  skips compilations and directly programs the FPGA
     -zip | -z   Create zip file
@@ -37,6 +38,7 @@ fi
 cd $JTROOT
 MODULES=$JTROOT/modules
 JTFRAME=$MODULES/jtframe
+SIDI=0
 
 if [ ! -e "$JTFRAME" ]; then
     echo "ERROR: cannot locate jtframe folder."
@@ -98,6 +100,8 @@ while [ $# -gt 0 ]; do
             PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:.
             PATH=$PATH:$HOME/altera/13.1/quartus/bin
             export PATH;;
+        -sidi)
+            SIDI=1;;            
         -add)
             ZIP=TRUE
             shift
@@ -119,6 +123,11 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
+
+if [[ "$SIDI" = 1 && "MIST" = mister ]]; then
+    echo "ERROR: You cannot select MiSTer and SIDI at the same time"
+    exit 1
+fi
 
 function escape_bars {
     echo ${1//\//\\/}
@@ -145,6 +154,85 @@ function copy_templates {
             cat $PRJPATH/mister/jt${PRJ}.tcl >> $PRJPATH/mister/jt${PRJ}.qsf            
         fi
     fi
+}
+
+function sidi_pins {
+    sed -i 's/Cyclone III/Cyclone IV E/g' $1
+    sed -i 's/EP3C25E144C8/EP4CE22F17C8/g' $1
+    sed -i 's/PIN_7 /PIN_G1 /g' $1
+    sed -i 's/PIN_54 /PIN_E1 /g' $1
+    sed -i 's/PIN_55 /PIN_M2 /g' $1 #two pines same clock
+    sed -i 's/PIN_144 /PIN_P16 /g' $1
+    sed -i 's/PIN_143 /PIN_P15 /g' $1
+    sed -i 's/PIN_142 /PIN_R16 /g' $1
+    sed -i 's/PIN_141 /PIN_R14 /g' $1
+    sed -i 's/PIN_137 /PIN_T15 /g' $1
+    sed -i 's/PIN_135 /PIN_T14 /g' $1
+    sed -i 's/PIN_133 /PIN_J16 /g' $1
+    sed -i 's/PIN_132 /PIN_J15 /g' $1
+    sed -i 's/PIN_125 /PIN_J14 /g' $1
+    sed -i 's/PIN_121 /PIN_K16 /g' $1
+    sed -i 's/PIN_120 /PIN_K15 /g' $1
+    sed -i 's/PIN_115 /PIN_J13 /g' $1
+    sed -i 's/PIN_114 /PIN_F16 /g' $1
+    sed -i 's/PIN_113 /PIN_F15 /g' $1
+    sed -i 's/PIN_112 /PIN_L16 /g' $1
+    sed -i 's/PIN_111 /PIN_L15 /g' $1
+    sed -i 's/PIN_110 /PIN_N15 /g' $1
+    sed -i 's/PIN_106 /PIN_N16 /g' $1
+    sed -i 's/PIN_136 /PIN_T10 /g' $1
+    sed -i 's/PIN_119 /PIN_T11 /g' $1
+    sed -i 's/PIN_65 /PIN_T12 /g' $1
+    sed -i 's/PIN_80 /PIN_T13 /g' $1
+    sed -i 's/PIN_105 /PIN_T2 /g' $1
+    sed -i 's/PIN_88 /PIN_R1 /g' $1
+    sed -i 's/PIN_126 /PIN_T3 /g' $1
+    sed -i 's/PIN_127 /PIN_T4 /g' $1
+    sed -i 's/PIN_91 /PIN_G15 /g' $1
+    sed -i 's/PIN_13 /PIN_H2 /g' $1
+
+    sed -i 's/PIN_49 /PIN_B14 /g' $1
+    sed -i 's/PIN_44 /PIN_C14 /g' $1
+    sed -i 's/PIN_42 /PIN_C15 /g' $1
+    sed -i 's/PIN_39 /PIN_C16 /g' $1
+    sed -i 's/PIN_4 /PIN_B16 /g' $1
+    sed -i 's/PIN_6 /PIN_A15 /g' $1
+    sed -i 's/PIN_8 /PIN_A14 /g' $1
+    sed -i 's/PIN_10 /PIN_A13 /g' $1
+    sed -i 's/PIN_11 /PIN_A12 /g' $1
+    sed -i 's/PIN_28 /PIN_D16 /g' $1
+    sed -i 's/PIN_50 /PIN_B13 /g' $1
+    sed -i 's/PIN_30 /PIN_D15 /g' $1
+    sed -i 's/PIN_32 /PIN_D14 /g' $1
+    sed -i 's/PIN_83 /PIN_C3 /g' $1
+    sed -i 's/PIN_79 /PIN_C2 /g' $1
+    sed -i 's/PIN_77 /PIN_A4 /g' $1
+    sed -i 's/PIN_76 /PIN_B4 /g' $1
+    sed -i 's/PIN_72 /PIN_A6 /g' $1
+    sed -i 's/PIN_71 /PIN_D6 /g' $1
+    sed -i 's/PIN_69 /PIN_A7 /g' $1
+    sed -i 's/PIN_68 /PIN_B7 /g' $1
+    sed -i 's/PIN_86 /PIN_E6 /g' $1
+    sed -i 's/PIN_87 /PIN_C6 /g' $1
+    sed -i 's/PIN_98 /PIN_B6 /g' $1
+    sed -i 's/PIN_99 /PIN_B5 /g' $1
+    sed -i 's/PIN_100 /PIN_A5 /g' $1
+    sed -i 's/PIN_101 /PIN_B3 /g' $1
+    sed -i 's/PIN_103 /PIN_A3 /g' $1
+    sed -i 's/PIN_104 /PIN_A2 /g' $1
+    sed -i 's/PIN_58 /PIN_A11 /g' $1
+    sed -i 's/PIN_51 /PIN_B12 /g' $1
+    sed -i 's/PIN_85 /PIN_C9 /g' $1
+    sed -i 's/PIN_67 /PIN_C8 /g' $1
+    sed -i 's/PIN_60 /PIN_A10 /g' $1
+    sed -i 's/PIN_64 /PIN_B10 /g' $1
+    sed -i 's/PIN_66 /PIN_D8 /g' $1
+    sed -i 's/PIN_59 /PIN_B11 /g' $1
+    sed -i 's/PIN_33 /PIN_C11 /g' $1
+    sed -i 's/PIN_43 /PIN_R4 /g' $1
+    sed -i 's/PIN_31 /PIN_B1 /g' $1
+    sed -i 's/PIN_46 /PIN_D1 /g' $1
+    sed -i 's/PIN_90 /PIN_G16 /g' $1
 }
 
 echo ==============================================
@@ -178,6 +266,9 @@ if [ $SKIP_COMPILE = FALSE ]; then
     LOG="$JTROOT/log/$MIST/jt$PRJ.log"
     echo Log file: $LOG
     copy_templates
+    if [ "$SIDI" = 1 ]; then
+        sidi_pins jt${PRJ}.qsf
+    fi
     # Prepare macros
     for m in $MACROS; do
         echo -e "\n" set_global_assignment -name VERILOG_MACRO \"$m\" >> jt$PRJ.qsf
@@ -226,11 +317,17 @@ if [ $ZIP = TRUE ]; then
         exit 1
     fi
     cp $RBF $RELEASE.rbf
-    zip --update --junk-paths releases/$MIST/${RELEASE}.zip ${RELEASE}.rbf README.txt $* \
+    ZIPFOLDER=$MIST
+    if [ "$SIDI" = 1 ]; then
+        ZIPFOLDER=sidi
+    fi
+    mkdir -p releases/$ZIPFOLDER
+    zip --update --junk-paths releases/$ZIPFOLDER/${RELEASE}.zip ${RELEASE}.rbf README.txt $* \
         $(append_if_exists rom/{$PRJ/build_rom.sh,$PRJ/build_rom.ini,build_rom_$PRJ.bat} doc/jt$PRJ.txt )
     if [ -e $JTROOT/../jtbin ]; then
         if [ "$MIST" = mist ]; then
-            cp releases/$MIST/${RELEASE}.zip $JTROOT/../jtbin/$MIST
+            mkdir -p $JTROOT/../jtbin/$ZIPFOLDER
+            cp releases/$ZIPFOLDER/${RELEASE}.zip $JTROOT/../jtbin/$ZIPFOLDER
         else
             # MiSTer
             # Add MRA files
